# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Tests
email: admin@e-jambon.com
description: > # this means to ignore newlines until "baseurl:"
  Aucune description pour ce blog. Il n'est pas sensé être déployé tel quel.
  Son unique intérêt réside dans le fait qu'il me sert de base pour procéder à des tests sur Jekyll.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: e_jambon
github_username:  e-jambon

# Build settings
markdown: kramdown
